trainer:
    gpus: 1
    min_epochs: 5
    max_epochs: 5
    #min_steps: 300
    #max_steps: 300
    #limit_train_batches: 0.05
    #limit_val_batches: 0.05
    precision: 16
    accumulate_grad_batches: 1
    gradient_clip_val: 1
    auto_lr_find: false
    check_val_every_n_epoch: 1
test_trainer:
    gpus: 1
    min_epochs: 10
    max_epochs: 10
    #min_steps: 750
    #max_steps: 750
    #limit_train_batches: 0.05
    #limit_val_batches: 0.05
    precision: 16
    accumulate_grad_batches: 1
    gradient_clip_val: 1
    auto_lr_find: false
    check_val_every_n_epoch: 1
scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.9
    verbose: false
schedule_interval: epoch
lr: 1e-6
lr_ft: 1e-6
